INSERT INTO game('game_name') VALUES('Sleeping Queens');
INSERT INTO game('game_name') VALUES('Mancala');
INSERT INTO game('game_name') VALUES('Tenzi');
INSERT INTO game('game_name') VALUES('Taboo');
INSERT INTO game('game_name') VALUES('Yes! and...');
INSERT INTO game('game_name') VALUES('Tangrams');
INSERT INTO game('game_name') VALUES('Chess');
INSERT INTO game('game_name') VALUES('checkers');
INSERT INTO game('game_name') VALUES('Backgammon');
INSERT INTO game('game_name') VALUES('Big Boggle');
INSERT INTO game('game_name') VALUES('Mantis');
INSERT INTO game('game_name') VALUES('Poetry for Ugh');
INSERT INTO game('game_name') VALUES('Chameleon');
INSERT INTO game('game_name') VALUES('Trivial Pursuit');
INSERT INTO game('game_name') VALUES('Telestrations');
INSERT INTO game('game_name') VALUES('Pun Intended');
INSERT INTO game('game_name') VALUES('Mexican Dominoes');
INSERT INTO game('game_name') VALUES('Rheinländer');
INSERT INTO game('game_name') VALUES('Tapple');
INSERT INTO game('game_name') VALUES('What Do You Meme?');
INSERT INTO game('game_name') VALUES('The Golden Ticket');
INSERT INTO game('game_name') VALUES('Qwirkle');
INSERT INTO game('game_name') VALUES('Silver & Gold');
INSERT INTO game('game_name') VALUES('Point Salad');
INSERT INTO game('game_name') VALUES('Splendor');
INSERT INTO game('game_name') VALUES('Planet X');
INSERT INTO game('game_name') VALUES('Waynesboro-opoly');
INSERT INTO game('game_name') VALUES('Risk');
INSERT INTO game('game_name') VALUES('Square up');
INSERT INTO game('game_name') VALUES('Gravity Maze');
INSERT INTO game('game_name') VALUES('Blokus');
INSERT INTO game('game_name') VALUES('Simon');
INSERT INTO game('game_name') VALUES('Dominion');
INSERT INTO game('game_name') VALUES('Planted');
INSERT INTO game('game_name') VALUES('Battleship');
INSERT INTO game('game_name') VALUES('Labyrinth');
INSERT INTO game('game_name') VALUES('SORRY!');
INSERT INTO game('game_name') VALUES('Stratego');
INSERT INTO game('game_name') VALUES('Clue');
INSERT INTO game('game_name') VALUES('Magic the Gathering');
INSERT INTO game('game_name') VALUES('Pictionary');
INSERT INTO game('game_name') VALUES('Guess Who');
INSERT INTO game('game_name') VALUES('Tiki Topple');
INSERT INTO game('game_name') VALUES('Rollick!');
INSERT INTO game('game_name') VALUES('Yahtzee');
INSERT INTO game('game_name') VALUES('Settlers of Catan');
INSERT INTO game('game_name') VALUES('Throw Throw Burrito');
INSERT INTO game('game_name') VALUES('Othello');
INSERT INTO game('game_name') VALUES('Ticket to Ride');
INSERT INTO game('game_name') VALUES('Outer Rim');
INSERT INTO game('game_name') VALUES('Hues & Cues');
INSERT INTO game('game_name') VALUES('Suspend');
INSERT INTO game('game_name') VALUES('Kingdomino');
INSERT INTO game('game_name') VALUES('Happy Salmon');
INSERT INTO game('game_name') VALUES('One Night Ultimate Werewolf');
INSERT INTO game('game_name') VALUES('Exploding Kittens');
INSERT INTO game('game_name') VALUES('Here to Slay');
INSERT INTO game('game_name') VALUES('Code Names');
INSERT INTO game('game_name') VALUES('Rook');
INSERT INTO game('game_name') VALUES('Take 2');
INSERT INTO game('game_name') VALUES('Pirate Fluxx');
INSERT INTO game('game_name') VALUES('Dutch Blitz');
INSERT INTO game('game_name') VALUES('Guillotine');
INSERT INTO game('game_name') VALUES('Mad Gab');
INSERT INTO game('game_name') VALUES('Sumoku');
INSERT INTO game('game_name') VALUES('Uno');
INSERT INTO game('game_name') VALUES('Rummikub');
INSERT INTO game('game_name') VALUES('Skip Bo');
INSERT INTO game('game_name') VALUES('LCR');
INSERT INTO game('game_name') VALUES('Blink');
INSERT INTO game('game_name') VALUES('Puzzle It');
INSERT INTO game('game_name') VALUES('Uno Dare');